In [1]:
import numpy as np # linear algebra
import pandas as pd

In [2]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import mean_squared_error as MSE

In [3]:
file_path = 'Washington_price_dataset.csv'
dataset = pd.read_csv(file_path)
dataset.head(1)

date     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 0:00  313000.0         3        1.5         1340      7912   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   

   yr_renovated                street       city  statezip country  
0          2005  18810 Densmore Ave N  Shoreline  WA 98133     USA

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   int64  
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [5]:
dataset.values

array([['2014-05-02 0:00', 313000.0, 3, ..., 'Shoreline', 'WA 98133',
        'USA'],
       ['2014-05-02 0:00', 2384000.0, 5, ..., 'Seattle', 'WA 98119',
        'USA'],
       ['2014-05-02 0:00', 342000.0, 3, ..., 'Kent', 'WA 98042', 'USA'],
       ...,
       ['2014-07-09 0:00', 416904.1667, 3, ..., 'Renton', 'WA 98059',
        'USA'],
       ['2014-07-10 0:00', 203400.0, 4, ..., 'Seattle', 'WA 98178',
        'USA'],
       ['2014-07-10 0:00', 220600.0, 3, ..., 'Covington', 'WA 98042',
        'USA']], dtype=object)

In [6]:
dataset.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [7]:
dataset.describe

<bound method NDFrame.describe of                  date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 0:00  3.130000e+05         3       1.50         1340   
1     2014-05-02 0:00  2.384000e+06         5       2.50         3650   
2     2014-05-02 0:00  3.420000e+05         3       2.00         1930   
3     2014-05-02 0:00  4.200000e+05         3       2.25         2000   
4     2014-05-02 0:00  5.500000e+05         4       2.50         1940   
...               ...           ...       ...        ...          ...   
4595  2014-07-09 0:00  3.081667e+05         3       1.75         1510   
4596  2014-07-09 0:00  5.343333e+05         3       2.50         1460   
4597  2014-07-09 0:00  4.169042e+05         3       2.50         3010   
4598  2014-07-10 0:00  2.034000e+05         4       2.00         2090   
4599  2014-07-10 0:00  2.206000e+05         3       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   int64  
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [9]:
dataset['country'].values

array(['USA', 'USA', 'USA', ..., 'USA', 'USA', 'USA'], dtype=object)

In [10]:
dataset['city'].drop_duplicates().values

array(['Shoreline', 'Seattle', 'Kent', 'Bellevue', 'Redmond',
       'Maple Valley', 'North Bend', 'Lake Forest Park', 'Sammamish',
       'Auburn', 'Des Moines', 'Bothell', 'Federal Way', 'Kirkland',
       'Issaquah', 'Woodinville', 'Normandy Park', 'Fall City', 'Renton',
       'Carnation', 'Snoqualmie', 'Duvall', 'Burien', 'Covington',
       'Inglewood-Finn Hill', 'Kenmore', 'Newcastle', 'Mercer Island',
       'Black Diamond', 'Ravensdale', 'Clyde Hill', 'Algona', 'Skykomish',
       'Tukwila', 'Vashon', 'Yarrow Point', 'SeaTac', 'Medina',
       'Enumclaw', 'Snoqualmie Pass', 'Pacific', 'Beaux Arts Village',
       'Preston', 'Milton'], dtype=object)

In [11]:
dataset['country'].drop_duplicates().values

array(['USA'], dtype=object)

In [12]:
dataset['street'].drop_duplicates().values

array(['18810 Densmore Ave N', '709 W Blaine St',
       '26206-26214 143rd Ave SE', ..., '759 Ilwaco Pl NE',
       '5148 S Creston St', '18717 SE 258th St'], dtype=object)

In [13]:
dataset[['yr_built']].drop_duplicates().values.reshape(1,-1)

array([[1955, 1921, 1966, 1963, 1976, 1938, 1989, 1985, 1945, 1948, 1909,
        1980, 1939, 1965, 1956, 1997, 1987, 1983, 1923, 1954, 2005, 1991,
        1959, 1920, 1979, 1951, 1967, 2004, 2014, 1995, 1944, 1992, 1957,
        1978, 1974, 1950, 1990, 1949, 1968, 1977, 1996, 2001, 2000, 1929,
        2006, 2008, 2009, 2012, 2013, 2007, 1986, 1973, 1988, 1900, 1928,
        1982, 1960, 2003, 1998, 1942, 1908, 1958, 1971, 1975, 1961, 1924,
        1902, 1962, 1953, 1999, 1994, 1930, 1984, 2010, 1912, 1947, 1916,
        1940, 1970, 1952, 1964, 1926, 1905, 1969, 1903, 1943, 1993, 1946,
        1910, 1904, 1981, 1906, 1922, 2011, 2002, 1917, 1913, 1914, 1937,
        1925, 1932, 1918, 1972, 1941, 1919, 1936, 1911, 1927, 1931, 1901,
        1907, 1915, 1935, 1933, 1934]], dtype=int64)

In [14]:
dataset['yr_renovated'].drop_duplicates().values.reshape(1,-1)

array([[2005,    0, 1992, 1994, 2010, 1988, 2009, 1969, 2000, 1979, 1989,
        2014, 1999, 2003, 1983, 1997, 1912, 1923, 1954, 2011, 2001, 2013,
        2006, 1972, 1985, 1998, 2004, 1958, 2008, 1970, 1982, 1986, 1996,
        2002, 1971, 1990, 1956, 1945, 1984, 2012, 1993, 2007, 1981, 1974,
        1963, 1968, 1995, 1934, 1953, 1966, 1955, 1987, 1960, 1978, 1980,
        1948, 1991, 1913, 1977, 1975]], dtype=int64)

In [16]:
dataset['condition'].value_counts(normalize=True)

condition
3    0.625000
4    0.272174
5    0.094565
2    0.006957
1    0.001304
Name: proportion, dtype: float64

In [17]:
X=dataset[['bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view',
           'condition','sqft_above','sqft_basement','yr_built','yr_renovated']]
Y=dataset[['price']]

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [19]:
dtr=DecisionTreeRegressor(max_depth=10,min_samples_leaf=0.1,random_state=1)

In [20]:
dtr.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=10, min_samples_leaf=0.1, random_state=1)

In [21]:
y_pred=dtr.predict(X_test)
MSE(y_pred,y_test)

84132732492.48367

In [22]:
y_pred_train=dtr.predict(X_train)
MSE(y_pred_train,y_train)

318223050321.82117

In [23]:
MSE_dtr_cv=-cross_val_score(dtr,X_train,y_train,cv=10,scoring='neg_mean_squared_error',n_jobs=-1)
MSE_dtr_cv.mean()

323642598168.51697

In [25]:
model=LinearRegression()

In [27]:
model.fit(X_train,y_train)

LinearRegression()

In [28]:
y_pred=model.predict(X_test)
MSE(y_pred,y_test)

65830113923.787346

In [29]:
model.coef_

array([[-5.34857267e+04,  5.93704684e+04, -3.17986053e+01,
        -6.56875920e-01,  3.19942164e+04,  5.88171821e+05,
         3.54391622e+04,  3.57667168e+04,  2.90980695e+02,
         2.57820803e+02, -2.19704939e+03,  8.23316006e+00]])

In [30]:
model.intercept_

array([4214518.32963384])

In [31]:
model.score(X_train,y_train)

0.19597906586468727

In [32]:
model.score(X_test,y_test)

0.4601982496971059

In [33]:
dataset2=dataset.drop(['date','city','street','statezip','country','price'],axis=1)
dataset2.corr()

bedrooms  bathrooms  sqft_living  sqft_lot    floors  \
bedrooms       1.000000   0.545920     0.594876  0.068819  0.177895   
bathrooms      0.545920   1.000000     0.760952  0.107837  0.486428   
sqft_living    0.594876   0.760952     1.000000  0.210642  0.344512   
sqft_lot       0.068819   0.107837     0.210642  1.000000  0.003750   
floors         0.177895   0.486428     0.344512  0.003750  1.000000   
waterfront    -0.003483   0.076232     0.117643  0.017241  0.022024   
view           0.111028   0.211960     0.311103  0.073907  0.031211   
condition      0.025080  -0.119994    -0.062560  0.000558 -0.275013   
sqft_above     0.484705   0.689918     0.876592  0.216455  0.522814   
sqft_basement  0.334165   0.298020     0.446417  0.034842 -0.255510   
yr_built       0.142461   0.463498     0.287340  0.050706  0.467481   
yr_renovated  -0.061082  -0.215886    -0.122476 -0.022730 -0.233996   

               waterfront      view  condition  sqft_above  sqft_basement  \
bedrooms        -0.003483  0.111028   0.025080    0.484705       0.334165   
bathrooms        0.076232  0.211960  -0.119994    0.689918       0.298020   
sqft_living      0.117643  0.311103  -0.062560    0.876592       0.446417   
sqft_lot         0.017241  0.073907   0.000558    0.216455       0.034842   
floors           0.022024  0.031211  -0.275013    0.522814      -0.255510   
waterfront       1.000000  0.360935   0.000352    0.078911       0.097501   
view             0.360935  1.000000   0.063077    0.174327       0.321602   
condition        0.000352  0.063077   1.000000   -0.178196       0.200632   
sqft_above       0.078911  0.174327  -0.178196    1.000000      -0.038723   
sqft_basement    0.097501  0.321602   0.200632   -0.038723       1.000000   
yr_built        -0.023563 -0.064465  -0.399698    0.408535      -0.161675   
yr_renovated     0.008625  0.022967  -0.186818   -0.160426       0.043125   

               yr_built  yr_renovated  
bedrooms       0.142461     -0.061082  
bathrooms      0.463498     -0.215886  
sqft_living    0.287340     -0.122476  
sqft_lot       0.050706     -0.022730  
floors         0.467481     -0.233996  
waterfront    -0.023563      0.008625  
view          -0.064465      0.022967  
condition     -0.399698     -0.186818  
sqft_above     0.408535     -0.160426  
sqft_basement -0.161675      0.043125  
yr_built       1.000000     -0.321342  
yr_renovated  -0.321342      1.000000

#sqft_living snd sqft_above are highly correlated bathrooms and sqft_living are highly correlated too bathrooms and sqft_above are highly correlated too Hence Multicollinearity is a problem